### PR TITLE
allow import react components, not only renderer

### PR DESCRIPTION
**Pull request by pYr0x**
in the past it was only possible to import react renderer like

``` javascript
export default function(ctx){
  return <div>Hello, {ctx.name}!</div>;
}
```

``` html
<div>Hello, {ctx.name}!</div>
```

with writing `import rendererFromJSX from './templates/react-html.jsx';`

however you want to import a whole react component written in jsx. this does not work.

```
import React from 'react';
import ReactDOM from 'react-dom';

let Component = React.createClass({
    render: function () {
        return (
            <div>my component!</div>
        );
    }
});

ReactDOM.render(
    <Component />,
    document.getElementById('demo')
)
```

with this fix now you can import react components.

**the only breaking change is**
if you would like to import a .jsx file written in html like

```
<h1>hello world</h1>
```

**we expect that the content of the .jsx file is proper html and starts with an opening html tag**

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks! published.

**Comment by pYr0x** [comment]
@matthewp would we change to 1.0 beacuse we had a breaking change? 

> the only breaking change is
> if you would like to import a .jsx file written in html like
> 
> `<h1>hello world</h1>`
> 
> we expect that the content of the .jsx file is proper html and starts with an opening html tag

**Comment by matthewp** [comment]
It's not a breaking change since this is a new project :)

**Comment by pYr0x** [comment]
:) :+1:

**Pull request merged**
